baseURL: https://codaholic.com/
languageCode: en-us
title: Codaholic
paginate: 10
theme: ["PaperMod"]
rssLimit: 25

permalinks:
  posts: /:slug/

googleAnalytics: G-CJ1XGSZQKH
enableRobotsTXT: true
sitemap:
  changefreq: weekly
  priority: 0.8


params:
  env: production
  title: Codaholic
  author: Emmy Steven
  images: ["img/feature-image.webp"]
  description: Codaholic is a community created for those who want to 10x software engineers
  keywords: [Community, Software Engineer, Developer, Coding, Programming]
  SidebarRecentLimit: 5

  showBreadCrumbs: false
  showReadingTime: true
  showShareButtons: true
  showPostNavLinks: true
  ShowFullTextinRSS: true
  showCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  math: true

  privacypolicy: /pages/privacy

  label:
    text: "Codaholic"
    icon: "img/logo.webp"
    iconHeight: 35

  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: "Welcome to Codaholic, a thriving tech community dedicated to fueling your passion for technology.
    You get to connect with like-minded professionals, exchange knowledge, and stay up-to-date with the latest trends and innovations.
    Join us on this exciting journey of continuous learning and collaboration."
  
  socialIcons:
    - name: "rss"
      url: "https://codaholic.com/index.xml"
    - name: twitter
      url: https://twitter.com/codaholichq
    - name: youtube
      url: http://youtube.com/@codaholichq
    - name: linkedin
      url: https://www.linkedin.com/company/codaholichq
    - name: github
      url: https://github.com/codaholichq
    - name: twitch
      url: https://www.twitch.tv/codaholichq
    - name: dev
      url: https://dev.to/codaholic
    - name: instagram
      url: https://instagram.com/codaholichq
    - name: medium
      url: https://medium.com/codaholic

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: false
    linkFullImages: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: posts
      weight: 1
    - identifier: podcasts
      name: Podcasts
      url: podcasts
      weight: 2
    - identifier: archives
      name: Archives
      url: archives
      weight: 3

disableKinds:
  - taxonomy

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true